controller_manager:
  ros__parameters:
    update_rate: 1000

    joint_effort_controller:
      type: effort_controllers/JointGroupEffortController
      
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
  
joint_effort_controller:
  ros__parameters:
    joints:
      - index_q1
      - index_q2
      - middle_q1
      - middle_q2
      - ring_q1
      - ring_q2
      - pinky_q1
      - pinky_q2
      - thumb_q1
      - thumb_q2 

    command_interfaces:
      - effort
    
    state_interfaces:
      - position
      - velocity
      - effort
